Repository xeokit/xeokit-sdk, pull requests merged in 2023-11, with the labels that each got.

#1214 FIX: force triangle instancing pick normals flat renderer
  src/viewer/scene/model/vbo/trianglesInstancing/TrianglesInstancingLayer.js
Labels: bug

#1222 Make measurements sliced by SectionPlanes #1217
  src/plugins/AngleMeasurementsPlugin/AngleMeasurement.js
  src/plugins/DistanceMeasurementsPlugin/DistanceMeasurement.js
  src/plugins/lib/html/Dot.js
  src/plugins/lib/html/Wire.js
  src/viewer/scene/math/math.js
  src/viewer/scene/model/dtx/triangles/renderers/TrianglesDataTextureColorRenderer.js
  src/viewer/scene/model/dtx/triangles/renderers/TrianglesDataTextureOcclusionRenderer.js
  src/viewer/scene/sectionPlane/SectionPlane.js
Labels: enhancement

#1227 Fix TreeView rendering when using globalizeObjectIds #1224
  src/viewer/metadata/MetaModel.js
Labels: bug

#1230 fix typo #1228
  src/viewer/scene/scene/Scene.js
Labels: bug

#1229 Movable SceneModel Objects
  examples/scenemodel/index.html
  examples/scenemodel/transforms_dtx_instancing_triangles.html
  examples/scenemodel/transforms_vbo_instancing_triangles.html
  src/viewer/scene/math/math.js
  src/viewer/scene/model/SceneModel.js
  src/viewer/scene/model/SceneModelEntity.js
  src/viewer/scene/model/SceneModelMesh.js
  src/viewer/scene/model/SceneModelTexture.js
  src/viewer/scene/model/SceneModelTextureSet.js
  src/viewer/scene/model/SceneModelTransform.js
  src/viewer/scene/model/dtx/triangles/DataTextureGenerator.js
  src/viewer/scene/model/dtx/triangles/DataTextureState.js
  src/viewer/scene/model/dtx/triangles/TrianglesDataTextureLayer.js
  src/viewer/scene/model/dtx/triangles/renderers/TrianglesDataTextureColorRenderer.js
  src/viewer/scene/model/dtx/triangles/renderers/TrianglesDataTextureDepthRenderer.js
  src/viewer/scene/model/dtx/triangles/renderers/TrianglesDataTextureEdgesColorRenderer.js
  src/viewer/scene/model/dtx/triangles/renderers/TrianglesDataTextureEdgesRenderer.js
  src/viewer/scene/model/dtx/triangles/renderers/TrianglesDataTextureNormalsRenderer.js
  src/viewer/scene/model/dtx/triangles/renderers/TrianglesDataTextureOcclusionRenderer.js
  src/viewer/scene/model/dtx/triangles/renderers/TrianglesDataTexturePickDepthRenderer.js
  src/viewer/scene/model/dtx/triangles/renderers/TrianglesDataTexturePickMeshRenderer.js
  src/viewer/scene/model/dtx/triangles/renderers/TrianglesDataTexturePickNormalsFlatRenderer.js
  src/viewer/scene/model/dtx/triangles/renderers/TrianglesDataTexturePickNormalsRenderer.js
  src/viewer/scene/model/dtx/triangles/renderers/TrianglesDataTextureSilhouetteRenderer.js
  src/viewer/scene/model/dtx/triangles/renderers/TrianglesDataTextureSnapDepthBufInitRenderer.js
  src/viewer/scene/model/dtx/triangles/renderers/TrianglesDataTextureSnapDepthRenderer.js
  src/viewer/scene/model/index.js
  src/viewer/scene/model/vbo/VBOSceneModelRenderers.js
  src/viewer/scene/model/vbo/linesInstancing/LinesInstancingLayer.js
  src/viewer/scene/model/vbo/pointsInstancing/PointsInstancingLayer.js
  src/viewer/scene/model/vbo/trianglesInstancing/TrianglesInstancingLayer.js
Labels: enhancement

#1257 FEATURE: Save and load object X-ray states in BCF
  examples/bookmarking/index.html
  examples/bookmarking/loadViewpoint_xrayAsZeroAlpha.html
  examples/bookmarking/saveViewpoint_xrayAsZeroAlpha.html
  src/plugins/BCFViewpointsPlugin/BCFViewpointsPlugin.js
Labels: feature
